name: Backend CI

on:
  push:
    paths: ["AIIA/backend/**", ".github/workflows/backend.yml"]
  pull_request:
    paths: ["AIIA/backend/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd AIIA/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black isort

      - name: Lint (black + isort)
        run: |
          cd AIIA/backend
          black --check .
          isort --check-only .

      - name: Run PyTest
        run: |
          cd AIIA/backend
          pytest -q